name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build the Docker image
        run: docker build -t skillsyncrecruiter/gpt-broker:latest .

      - name: Push to DockerHub
        run: docker push skillsyncrecruiter/gpt-broker:latest
